import random

def guess(x):
    randomNumber = random.randint(1, x)
    guess = 0
    while guess != randomNumber:
        guess = int(input(f"\nGuess a number between 1 and {x}: "))
        print("Your Guess Was: ", guess)
        if guess < randomNumber:
            print("Too Low")
        elif guess > randomNumber:
            print("Too High")
    print("\nYou Won")


def computerGuess(x):
    low = 1
    high = x
    feedback = ''
    print(f"Choose a number between 1 and {x}, keep it to yourself")
    while feedback != 'c':
        if low != high:
            guess = random.randint(low, high)
        else:
            guess = low         # Could also be high
        feedback = input(f'Is {guess} too high (H), too low (L) or correct (C)?').lower()
        if feedback == 'h':
            high = guess - 1
        elif feedback == 'l':
            low = guess + 1
    print(f"The computer guessed your number {guess}")

print ("1. You guess a number generated by the computer \n2. The computer guess a number of your choosing")
answer = int(input("Which game do you want to play? (1,2) "))
if answer == 1:
    value = int(input("What is the highest number you want the computer to be able to choose? "))
    guess(value)

if answer == 2:
    value = int(input("You will select a number between 1 and ? "))
    computerGuess(value)